usethis::use_testthat(3)

usethis::use_test("email_notification_helpers")
usethis::use_test("th2_pkg_local_helpers")

usethis::use_package("mockery")
usethis::use_package("glue")
usethis::use_package("testthat")
usethis::use_package("httr2")
usethis::use_package("rvest")
usethis::use_package("shinyalert")
usethis::use_package("bs4Dash")
usethis::use_package("RSQLite")
usethis::use_package("shiny")
usethis::use_package("RSQLite")
usethis::use_package("bs4Dash")
usethis::use_package("bs4Dash")
usethis::use_package("magrittr")
usethis::use_package("tidyverse")
devtools::install_github('jbryer/DTedit')
